from src.personal_assistant.common import ApplicationBaseError

class ContactBaseError(ApplicationBaseError): ...

class ContactNotFound(ContactBaseError): ...

class ContactExist(ContactBaseError): ...

class PhoneFormatError(ContactBaseError): ...

class EmailFormatError(ContactBaseError): ...

class BirthdayFormatError(ContactBaseError): ...
